### ISSUE TITLE
System setting

### ISSUE THREAD

**Issue by electrickite** [BobRay/DefaultResourceGroup#1]
Currently, the default resource group(s) are configured via a property set. I would like to  set this via a system setting. This would allow the default resource group to be customized per user and per context.

This could take the form of an additional getOption call: the package wouldn't need to create the setting. If the system setting was absent, the plugin would use its configured property set, preserving backward compatibility.

I'd be willing to submit a pull request if this sounds like a reasonable idea.

**Comment by BobRay** [comment]
I believe this will work already. getOption() will look for a User Setting, Context Setting, or System Setting (in that order) if there is no property with that name. So if you create a setting called drg_groups and remove any properties or property sets, it should use the setting.

Let me know if it works.

**Comment by electrickite** [comment]
I tried your suggestion. The system setting will work, but only if the drg_groups property is removed from the plugin's default property set. Would that change be reverted during a package update?

**Comment by BobRay** [comment]
I can't say for sure, since it was built with PackMan and I don't have access to the build script.

I'm almost sure that upgrading DefaultResourceGroup would revert the setting, but it's not a package that's likely to be updated often (if ever).

Upgrading MODX would have no effect on the setting.
